### ISSUE TITLE
入口文件（bin/hyperf.php）自定义常量，获取失败，使用 php bin/hyperf.php start 可以

### ISSUE THREAD

**Issue by xhh125zl** [hyperf/watcher#15]
入口文件（bin/hyperf.php）自定义常量，
使用 php bin/hyperf.php server:watch 启动后，常量调用失败（没有此常量定义）

但是 使用 php bin/hyperf.php start 是 可以 使用的

**Comment by limingxinleo** [comment]
server:watch 走的不是 hyperf.php 那个入口文件
