### ISSUE TITLE
删除 runtime/container 目录后报错

### ISSUE THREAD

**Issue by blacksheepaul** [hyperf/watcher#17]
![image](https://user-images.githubusercontent.com/26378591/116214046-eaac3300-a778-11eb-98a2-342fc1d0ce47.png)

与此同时，`php72 bin/hyperf.php start` 可以正常启动。

相关环境：

![image](https://user-images.githubusercontent.com/26378591/116214689-863da380-a779-11eb-9600-6286f7248678.png)

![image](https://user-images.githubusercontent.com/26378591/116214778-a1a8ae80-a779-11eb-8208-df91eeb17b04.png)

如果需要其他信息烦请提示我补充，谢谢~

**Comment by limingxinleo** [comment]
composer dump-autoload -o
