### ISSUE TITLE
ScanFileDriver 无法使用

### ISSUE THREAD

**Issue by sevendiscovery** [hyperf/watcher#5]
composer require hyperf/watcher --dev  安装下来的2.0.1 没有 ScanFileDriver 驱动

**Comment by limingxinleo** [comment]
composer require "hyperf/watcher:2.0.x-dev" --dev

**Comment by manyoubaby123** [comment]
![image](https://user-images.githubusercontent.com/9696271/87237875-09ca1600-c42e-11ea-8ab7-353085aedead.png)
驱动：ScanFileDriver,依赖注入没问题，注解注入会报错
 [ERROR] Call to a member function getMethod() on null[20] in /hyperf-skeleton/ap
p/Controller/IndexController.php
[ERROR] #0 /hyperf-skeleton/vendor/hyperf/http-server/src/CoreMiddleware.php(160
): App\Controller\IndexController->index()
#1 /hyperf-skeleton/vendor/hyperf/http-server/src/CoreMiddleware.php(112): Hyper
f\HttpServer\CoreMiddleware->handleFound(Object(Hyperf\HttpServer\Router\Dispatc
hed), Object(Hyperf\HttpMessage\Server\Request))
#2 /hyperf-skeleton/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(65):
 Hyperf\HttpServer\CoreMiddleware->process(Object(Hyperf\HttpMessage\Server\Requ
est), Object(Hyperf\Dispatcher\HttpRequestHandler))
#3 /hyperf-skeleton/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyp
erf\Dispatcher\AbstractRequestHandler->handleRequest(Object(Hyperf\HttpMessage\S
erver\Request))

**Comment by limingxinleo** [comment]
composer dump-autoload -o
